
                              BABBLE! 2.0 ORDER FORM


     Remit to:  Korenthal Associates, Inc.   Orders only: (800) KA-PROGS
                230 West 13th Street         Information: (212) 242-1790
                New York, New York 10011     FAX:         (212) 242-2599
                U.S.A.                       CompuServe:  [76004,2605]


     Babble! Registered Package              Qty ____ @  $25     $_________

     Babble! Site License, 5-10 users        Qty ____ @ $150     $_________

     Babble! Site License, 11-25 users       Qty ____ @ $350     $_________
     (See SITELIC.DOC for additional information)

               New York residents add applicable sales tax:      $_________

               Shipping and handling, US/Canada:  $4 per copy
                            All other countries:  $8 per copy    $_________

                                                        Total    $_________

     Payment by:  ( ) Check (U.S. funds only, drawn on a U.S. bank)

                  ( ) MasterCard  ( ) Visa  ( ) PO # ______________

     Card #: ____________________________________  Exp. Date: _____________

     Signature of card holder: ____________________________________________


     Name:    ____________________________________  Title: ________________

     Company: _____________________________________________________________

     Address: _____________________________________________________________

              _____________________________________________________________

              _____________________________________________________________

     Day Phone: ________________________  Evening: ________________________


     Disk format:  ( ) 5.25" acceptable  ( ) 3.5" required


     Where did you get your shareware copy of Babble!? ____________________

     ______________________________________________________________________

     Do you have any comments or suggestions to improve Babble!? __________

     ______________________________________________________________________

     [Distr. #BAB-CHANEL]
